name: tokenspiceenv
dependencies:
  - pip==9.0.1
  - numpy
  - matplotlib
  - pip:
    - enforce
    - pytest
    - web3
    - deprecated
    - pycryptodomex
    - tqdm
    - pytz
    - eth-account
    - eth-keys
    - eth-utils
    
